#!/bin/sh
# -*- mode:shell-script -*-
#
# $Id$
#
#	Remotely 'cat' a file, via SSH.

if [ $# = 0 ]; then
    cat <<EOF

	Usage: $0 USER@HOST:PATH/TO/FILE

	Print out the given remote file via SSH.

EOF
    exit 1
fi

RHOST=`echo "$1" | cut -d ':' -f 1`
RFILE=`echo "$1" | cut -d ':' -f 2`
shift

ssh "$RHOST" "cat '$RFILE'"
