#!/bin/sh
# -*- mode:shell-script -*-
#
# $Id$
#
#	Remotely 'cat' a file, via SSH.

usage ()
{
    cat <<EOF

	Usage: $0 USER@HOST:PATH/TO/FILE [PATH/TO/LOCAL/FILE]

	Compare given remote file to specified local file.

	If no local file is specified, it is assumed to be one with the same
	name as the remote file in the current directory.

	The environment variable REMOTE_PATH may be used to specify the
	remote path or just the host.

EOF
    exit 1
}

if [ $# = 0 ]; then
   usage
fi

RHOST=`echo "$1" | cut -d ':' -f 1`
RFILE=`echo "$1" | cut -d ':' -f 2`
LFILE=$2

if [ "$RHOST" = "$RFILE" ]; then
   if [ "$REMOTE_PATH" = "" ]; then
      cat <<EOF
Error:	No remote path specified.
	RHOST=$RHOST
	RFILE=$RFILE
EOF
      usage
   fi
   LFILE="$1"
   RHOST=`echo "$REMOTE_PATH" | cut -d ':' -f 1`
   RPATH=`echo "$REMOTE_PATH" | cut -d ':' -f 2`
   if [ "$RHOST" != "$RPATH" ]; then
      RFILE="$RPATH/$RFILE"
   fi
fi

if [ "$LFILE" = "" ]; then
    if [ "`echo '$RFILE' | cut -d '/' -f 1`" = "" ]; then
	LFILE=`basename "$RFILE"`
    else
	LFILE="$RFILE"
    fi
fi

# $2 could be a local directory:
if [ -d "$LFILE" ]; then
    LFILE=`echo "$LFILE" | cut -d ':' -f 1`/`basename "$RFILE"`
fi

echo "# Remote file = $RHOST:$RFILE"
ssh "$RHOST" "cat '$RFILE'" | diff -wu - "$LFILE"
